### ISSUE TITLE
regarding task 1

### ISSUE THREAD

**Issue by azcruze** [azcruze/mindkraft#1]
okay so here i am doing my first issue on git hub...looks like its basically a place where u can comment and send message and share your thoughts with others so yeah

**Comment by shalcrackzzz** [comment]
hiiiii

**Comment by azcruze** [comment]
hey yeah....i checked it again and i would like save my steps of creating a new issue
1. I created a new repository
2. Then i went to issues and created a new milestone
3.after creating a milestone i gave the deadline and stuff
4.then i came back to issues and gave new issues and gave title for that 
5.under milestone i connected  task 1
6. then under labels i have enhancement
7.now im texting under comments

**Comment by shalcrackzzz** [comment]
hoiii cruze

**Comment by shalcrackzzz** [comment]
boring cruzee

**Comment by shalcrackzzz** [comment]
https://www.bing.com/images/search?view=detailV2&ccid=3VKcX52c&id=0D61D4233FE9BDA7BD92EFB4554B31E4BA223015&thid=OIP.3VKcX52ccNx009ZLHgC7jQHaHa&mediaurl=https%3a%2f%2fpngimg.com%2fuploads%2fgithub%2fgithub_PNG67.png&exph=512&expw=512&q=github&simid=608006725089957975&FORM=IRPRST&ck=532EFDE9796AE7830AA3C5D91AE2D153&selectedIndex=74&itb=1

**Comment by azcruze** [comment]
![github-app-tips](https://github.com/azcruze/mindkraft/assets/153887343/4ae76edf-fb66-493a-b693-970ae6a4d0e8)

**Comment by azcruze** [comment]
@shalcracksss hi

**Comment by azcruze** [comment]
heyyyyyyyyyyyyyyy
